# Generated by Django 4.0.5 on 2022-09-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0004_takip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Takip',
        ),
    ]
