# Generated by Django 4.0.5 on 2022-09-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0007_remove_kitaplar_takipci_kuruluslar_takipci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuruluslar',
            name='takipci',
        ),
    ]
